name: same_test # 実行スクリプト名

on: [push] # 実行タイミング

jobs:
  io_test:
    name: Use Linux commands # テスト名
    runs-on: ubuntu-latest # 実行環境

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Permission Setting
        run: chmod +x gcd.sh test_gcd.sh

      - name: Test Run
        run: ./test_gcd.sh
