user001@yukiserver:~/repo15$ history
    1  exit
    2  ls
    3  ls /
    4  ls -a /
    5  ls / -a
    6  ls /root | cat
    7  pwd
    8  ls
    9  env
   10  LANG
   11  $LANG
   12  $TERM
   13  TERM
   14  ip a
   15  ls /etc/netplan/
   16  cat /etc/netplan/50-cloud-init.yaml
   17  sudo cat /etc/netplan/50-cloud-init.yaml
   18  sudo cat /etc/services | less
   19  ls /etc/netplan/
   20  networkctl ls
   21  networkctl list
   22  sudo ufw status
   23  sudo ufw allow 22/tcp
   24  sudo ufw allow 80/tcp
   25  sudo ufw enable
   26  sudo ufw status
   27  sudo ufw status verbose
   28  mkdir lesson08
   29  cd ./lesson08
   30  touch file
   31  ls
   32  ip -a
   33  history
   34  ip a
   35  sudo apt install net-tools
   36  netstat -t
   37  routes
   38  route
   39  sudo dpkg -l
   40  sudo dpkg -l | grep ssh
   41  ls .ssh
   42  sudo ls .ssh
   43  cd ..
   44  sudo apt install openssh-server
   45  sudo systemctl status
   46  sudo apt install apache2
   47  ps aux | grep apache
   48  sudo ufw status
   49  ip a
   50  clear
   51  history
   52  ip a
   53  sudo ufw status
   54  sudp apt install zip
   55  sudo apt install zip
   56  clear
   57  cd ./leso
   58  cd ./lesson08/
   59  vim file
   60  zip -e file.zip file
   61  ls
   62  cat file.zip
   63  cd ..
   64  ls
   65  mkdir lesson07
   66  ls
   67  cd ./lesson07
   68  echo same > file_A
   69  echo same > file_B
   70  ls
   71  diff file_A file_B
   72  echo $?
   73  echo diff
   74  echo diff | diff file_A
   75  echo $1
   76  echo $?
   77  cat /etc/sudoers | grep "user001" >> sudo-log.txt
   78  echo $?
   79  echo {PIPESTATUS}
   80  echo {PIPESTATUS[@]}
   81  echo ${PIPESTATUS}
   82  cat /etc/sudoers | grep "user001" >> sudo-log.txt
   83  echo ${PIPESTATUS}
   84  touch /root/file | : | echo "done"
   85  echo ${PIPESTATUS}
   86  echo ${PIPESTATUS[@]}
   87  touch /root/file | : | echo "done"
   88  echo ${PIPESTATUS[@]}
   89  test a = a
   90  echo $?
   91  test a = b
   92  echo $?
   93  [ a = b ]
   94  echo $?
   95  [ -n "a" ]; echo $?
   96  clear
   97  echo hello & echo world
   98  echo hello; echo world
   99  true && echo hello
  100  true || echo hello
  101  false || echo hello
  102  [ -f /bin/ls ] && echo "here is file" || echo "no file"
  103  [ -f /bin/sl ] && echo "here is file" || echo "no file"
  104  ls
  105  vim exit.sh
  106  fg
  107  vim 01_exit.sh &
  108  fg
  109  vim 01_exit.sh
  110  vim 02_if.sh
  111  chmod +x 02_if.sh
  112  ./02_if.sh
  113  ./02_if.sh 10 1
  114  vim 03_case.sh
  115  chmod +x 03_case.sh
  116  ./03_case.sh
  117  vim 04_while.sh
  118  chmod +x 04_while.sh
  119  ./04_while.sh
  120  vim 05.break.sh
  121  chmod +x 05.break.sh
  122  ./05_break.sh
  123  ls
  124  mv 05.break.sh 05_break.sh
  125  ls
  126  ./05_break.sh
  127  vim 05_break.sh
  128  vim 06_for.sh
  129  chmod +x 06_for.sh
  130  ./06_for.sh
  131  mkdir diary1 diary2
  132  touch diary1/day[1..5]
  133  ls diarry1/
  134  ls diary1/
  135  touch diary1/day{1..5}
  136  ls diary1/
  137  rm diary1/'day[1..5]'
  138  ls diary1/
  139  touch diary2/day{6..8}
  140  ls diary2/
  141  num=1
  142  echo $num
  143  ls diary1 | while read fn; do echo $fn; done
  144  ls diary1 | while read fn; do cp diary1/$fn diary2/${fn}_cp; done
  145  ls diary1
  146  ls diary2
  147  vim 10_filereader.sh
  148  chmod +x 10_filereader.sh
  149  ./10_filereader.sh
  150  vim 10_filereader.sh
  151  sudo apt install cowsay fortune
  152  git clone http://github.com/possatti/pokemonsay
  153  cd pokemonsay
  154  ls
  155  ./install.sh
  156  fortune | pokemonsay
  157  /home/user001/bin/pokemonsay
  158  /home/user001/bin/pokemonsay hello
  159  pokemonsay hey
  160  /home/user001/bin/pokemonsay hoho
  161  ls
  162  cd ..
  163  test $num1 -gt $num2 && echo "num1 is bigger"
  164  test $num1 -gt $num2 && echo "num1 is bigger" 10 1
  165  num1=10
  166  num2=1
  167  test $num1 -gt $num2 && echo "num1 is bigger"
  168  [ $num1 -gt $num2 ] && echo "num1 is bigger"
  169  man ls &
  170  ps
  171  kill -p 7882
  172  kill 7882
  173  ps
  174  pkill 7882
  175  ps
  176  kill --help
  177  kill -l
  178  kill -s 1 -p 7882
  179  kill -s 1 -p7882
  180  kill -9 7882
  181  ps
  182  fg 7882
  183  ps --help
  184  ps l
  185  pstree
  186  bg
  187  fg 1
  188  ps l
  189  man ls &
  190  ps l
  191  fg 1
  192  ps l
  193  clear
  194  ls
  195  cd ..
  196  ls
  197  cd ./lesson08
  198  ls
  199  seq -w 0 999 | while read n ; do unzip -p -P $n file.zip ; done
  200  ls
  201  clear
  202  ip -a
  203  history
  204  ip a
  205  clear
  206  cd ..
  207  ls
  208  cat key
  209  cat key >> .ssh/authorized_keys
  210  ls
  211  ssh -p 2622 user001@172.16.185.131
  212  ssh-keygen -t ed25519
  213  ls ~/.ssh
  214  ssh -p 2622 user001@172.16.185.131
  215  pwd
  216  ls /etc
  217  cat /etc/passwd
  218  ls - a
  219  ls -a
  220  ls /etc | gret ufw
  221  ls /etc | grep ufw
  222  sudo vim /etc/ufw/ufw.conf
  223  sudo ufw status
  224  sudo service --status-all
  225  sudo systemctl
  226  cat /etc/ssh/sshd_config
  227  cat /etc/ssh/sshd_config | less
  228  sudo vim /etc/ssh/sshd_config
  229  cat /etc/profile
  230  cat .profile
  231  cp .profile .profile.org
  232  cp .bashrc .bashrc.org
  233  vim .bashrc
  234  echo .profile
  235  vim .profile
  236  echo 'echo "./bashrcが読み込まれました"' >> .bashrc
  237  tail .bashrc
  238  exit
  239  ps
  240  exit
  241  ps
  242  exit
  243  mv .bashrc.org .bashrc
  244  mv .profile.org .profile
  245  ls -a
  246  vim .bashrc
  247  vim bin/my_cmd
  248  chmod +x bin/my_cmd
  249  source .bashrc
  250  my_cmd
  251  whoami
  252  who
  253  w
  254  cat /etc/login.defs
  255  vim /etc/login.defs
  256  sudo adduser sato
  257  sudo groupadd test_group
  258  sudo gpasswd -a sato test_group
  259  cat /etc/group
  260  sudo groupdel test_group
  261  cat /etc/group
  262  su root
  263  sudo -s
  264  ssh -p 2622 sato-yuki@202.247.58.211
  265  ls /etc/
  266  sudo ufw status
  267  sleep 100&
  268  ps
  269  which leep
  270  which sleep
  271  sleep 1
  272  ps
  273  od /bin/sleep
  274  clear
  275  pstres
  276  pstree
  277  ls /proc
  278  sleep 3; echo "hello"
  279  echo $$
  280  ps
  281  echo $$
  282  mkdir lesson10
  283  cd ./lesson10
  284  vim 01-pg.sh
  285  chmod x 01-pg.sh
  286  chmod --help
  287  ./01-pg.sh
  288  ps aux
  289  top
  290  nice -n 5 sleep 100&
  291  kill -l
  292  clear
  293  which sleep
  294  ps
  295  vim 04-fork.sh
  296  rm 04-fork.sh
  297  vim 04-fork.c
  298  sudo apt install gcc
  299  ls
  300  ./04-fork
  301  gcc 04-fork.c -0 04-fork
  302  gcc 04-fork.c -o 04-fork
  303  vim 04-fork.c
  304  gcc 04-fork.c -o 04-fork
  305  ./04-fork
  306  ps
  307  ./04-fork
  308  clea
  309  rclear
  310  clear
  311  vim 05-exec.sh
  312  bash 05-exec.sh
  313  ps -ls
  314  ps -la
  315  bash 05-exec.sh &
  316  ps -u
  317  cd ..
  318  sudo parted -l
  319  ls /dev/sda
  320  ls /dev/
  321  df
  322  mkdir lesson11
  323  cd lesson11
  324  echo hello > a.txt
  325  ls
  326  seq 1 1000  > b.txt
  327  ls
  328  ls -l
  329  du -ah
  330  seq 1 1000 >> b.rxt
  331  seq 1 1000 >> b.txt
  332  du -ah
  333  rm ./b.rxt
  334  ls -l
  335  ls -ls
  336  clear
  337  df -i
  338  ls -lsi
  339  stat a.txt
  340  touch c.txt
  341  ls -ls
  342  ls -lsi
  343  ln a.txt a.hl
  344  ls
  345  ls -li
  346  cat a.hl
  347  echo "editted a.link" >> a.txt
  348  ls -lsi
  349  cat a.hl
  350  rm a.txt
  351  ls -l
  352  ls -lsi
  353  ls
  354  echo "HELLO" > file2.org
  355  ls
  356  ln -s file2.sl
  357  ls -li
  358  rm file2.sl
  359  ln -s file2.org file2.sl
  360  ls -li
  361  getconf PAGE_SIZE
  362  echo $$
  363  pmap -x 18526
  364  time seq 1 1000000 > /run/shm/hoge
  365  time seq 1 1000000 > ~/hoge
  366  rm /run/shm/hoge
  367  rm ~/hoge
  368  cd ..
  369  ls
  370  cd /lesson11
  371  cd ./lesson11
  372  sleep 100 > hoge
  373  sleep 100 > hoge &
  374  lsof -p 37447
  375  seq 1 1000000 > hoge
  376  ls
  377  cat hoge > /dev/null
  378  time cat hoget > /dev/null
  379  man lsof | col -b > man.txt
  380  cat man.txt
  381  cat man.txt | less
  382  less man.txt
  383  ls
  384  rm man.txt
  385  lsof | grep man.txt
  386  cat /sys/devices/system/cpu/cpu0/cache/index0/size
  387  cat /sys/devices/system/cpu/cpu0/cache
  388  ls /sys/devices/system/cpu/cpu0/cache
  389  ls /sys/devices/system/cpu/cpu0/cache/index0 size
  390  cat  /sys/devices/system/cpu/cpu0/cache/index0 size
  391  cat  /sys/devices/system/cpu/cpu0/cache/index0/ size
  392  ls -l /dev/
  393  clear
  394  cd ..
  395  ls /dev
  396  cat /proc/cpuinfo
  397  ls /proc
  398  l
  399  l /proc
  400  lspici
  401  lspci
  402  lspci -vv
  403  lspci -vv | less
  404  echo $PATH
  405  sudo apt install cgroup-tools
  406  ls /sys/fs/cgroup/
  407  mkdir lesson12
  408  cd ./lesson12
  409  ls /sys/fs/cgroup/cpu*
  410  ls /sys/fs/cgroup/cpu.stat
  411  cat /sys/fs/cgroup/cpu.stat
  412  sudo vim /etc/systemd/system/user-user002.slice
  413  sudo systemctl daemon-reexec
  414  sudo systemctl daemon-reload
  415  sudo systemctl start user-user002.slice
  416  sudo systemd-run --uid=user002 --slice=user-user002.slice --scope bash
  417  ls pid
  418  sudo systemctl start user-user002.slice
  419  sudo systemd-run --uid=user002 --slice=user-user002.slice --scope bash
  420  cd ..
  421  sudo apt install docker.io
  422  which docker
  423  cat /etc/group
  424  sudo gpasswd -a user001 docker
  425  cat /etc/groupsudo systemctl start docker.service#
  426  sudo systemctl start docker.service
  427  sudo systemctl enable docker.service
  428  exit
  429  clear
  430  docker search ubuntu
  431  docker pull ubuntu:latest
  432  docker images
  433  docker run -it --name "UbuDoc" ubuntu:latest /bin/bash
  434  docker ps -a
  435  docker start UbuDoc
  436  docker ps -a
  437  docker exec -it UbuDock /bin/bash
  438  docker exec -it UbuDoc /bin/bash
  439  docker ps -a
  440  docker stop UbuDoc
  441  docker start UbuDoc
  442  docker exec -it UbuDoc /bin/bash
  443  docker ps -a
  444  docker commit UbuDoc my_image:20260523
  445  docker image
  446  docker images
  447  docker save my_image > ~/lesson12/apa2img.tar.gz
  448  docker load < ~/lesson12/apa2img.tar.gz
  449  docker images
  450  type ls
  451  python3
  452  ls
  453  vim main.c
  454  cpp main.c
  455  ls
  456  cpp main.c main.i
  457  ls
  458  cat main.i | less
  459  gcc -c main.c
  460  od main.o
  461  gcc -o main main.c
  462  ls
  463  ./main
  464  gccmain2.c calc.h calc.c
  465  ls
  466  clear
  467  mkdir kadai3
  468  touch README
  469  pwd
  470  sudo apt install git
  471  git config --list
  472  git config --global user.name "yuki"
  473  ls -a
  474  cat .gitconfig
  475  git config --global user.email "a26112ys@aiit.ac.jp"
  476  cat .gitconfig
  477  git config --global core.editor vim
  478  mkdir lesson13
  479  cd ./lesson1
  480  cd ./lesson13
  481  git init
  482  ls
  483  ls -a
  484  clear
  485  ls .git/
  486  git status
  487  touch README
  488  vim README
  489  git add README
  490  git status
  491  touch file1
  492  git add file1
  493  git status
  494  git commit
  495  echo "hoge" > README
  496  git status
  497  git restore
  498  git restore README
  499  cat README
  500  top
  501  nslookup www.youtube.com
  502  clear
  503  tail -f
  504  curl https://www.jma.go.jp/bosai/forecast/data/forecast/140000.json
  505  curl　-s  https://www.jma.go.jp/bosai/forecast/data/forecast/140000.json
  506  cd ..
  507  clear
  508  ls
  509  mkdir kadai3_test
  510  cd ./kadai3_test/
  511  mkdir weather_logs
  512  ls
  513  curl -s -o raw.json -w "%{http_code}" https://www.jma.go.jp/bosai/forecast/data/forecast/140000.json
  514  ls
  515  vim raw.json
  516  ls ./weather_logs/
  517  vim raw.json
  518  exit
  519  ls
  520  cd ./kadai3_test/
  521  mkdir user
  522  rm user
  523  rm ./user
  524  ls
  525  rm -r ./user/
  526  ls
  527  mkdir data
  528  mkdir backup
  529  ls
  530  touch backup.sh
  531  vim backup
  532  vim backup.sh
  533  pwd
  534  vim backup.sh
  535  cat backup.sh
  536  clear
  537  ls -a
  538  ls -l
  539  ls -lah
  540  chmod +x backup.sh
  541  echo "hello" > ./data
  542  echo "hello" > data/hello.txt
  543  ls -lah ./data
  544  ./backup.sh
  545  ls ./backup
  546  cd ..
  547  mkdir lesson14
  548  cd ./lesson14
  549  git init
  550  ls -a
  551  touch file01
  552  ls
  553  git status
  554  git add file01
  555  git status
  556  clear
  557  git status
  558  git config --list
  559  git commit
  560  git status
  561  git log
  562  ls -lah
  563  ls .git
  564  ls .git/branches
  565  ls .ssh
  566  ls ~/.ssh
  567  cat ~/.ssh/id_ed25519.pub
  568  cd ..
  569  rm -rf ./lesson14
  570  ls
  571  git clone git@github.com:youxiberlin/ss-lesson14.git
  572  ls
  573  cd ./ss-lesson14/
  574  ls
  575  git status
  576  touch file-01
  577  git add file-01
  578  git commit -m "test push"
  579  git push
  580  cd ..
  581  git clone git@github.com:sa004828-ai/lesson14.git
  582  cd ./lesson14/
  583  ls
  584  vim file-01
  585  git status
  586  git add
  587  git status
  588  git add .
  589  git status
  590  git commit -m "Updated comment"
  591  git push
  592  git restore
  593  git revert HEAD
  594  git status
  595  cd ..
  596  rm -rf ./lesson14
  597  ls
  598  history
  599  git clone git@github.com:sa004828-ai/lesson14.git
  600  cd ./lesson14
  601  ls
  602  cd ..
  603  ls
  604  cd ..
  605  cd ./kadai3_test
  606  ls
  607  cd ./user001
  608  l
  609  ls
  610  cd ./kadai3_test
  611  ls
  612  cd //
  613  cd ..
  614  cd ~
  615  ls
  616  pwd
  617  rm -rf ./kadai3
  618  ls
  619  rm -rf ./kadai3_test
  620  cd /
  621  ls
  622  ls /var
  623  ls /var/backups/
  624  ls /var/log
  625  cat /var/log/faillog
  626  cat /proc/cpuinfo
  627  lspci
  628  clear
  629  less lspci
  630  lspci
  631  lspci -vv
  632  ls /proc
  633  lsusb
  634  lsmod
  635  runlevel
  636  docker ps
  637  docker images
  638  docker version
  639  docker ps
  640  docker ps -a
  641  docker images
  642  docker stop UbuDoc
  643  docker images
  644  docker ps -a
  645  docker rm UbuDoc
  646  docker system prune
  647  docker ps -a
  648  docker images
  649  docker system prune -a --volumes
  650  docker images
  651  history
  652  exit
  653  ls
  654  mkdir kadai3
  655  cd ./kadai3/
  656  mkdir incoming_data
  657  cd ./incoming_data/
  658  echo "date,item,quantity,price" > purchase_A.csv
  659  ls
  660  cat purchase_A.csv
  661  rm purchase_A.csv
  662  ls
  663  echo "date,manager,item,quantity,price" > purchase_A.csv
  664  echo "2025-06-01,Paul Smith,PC,2,120000" >> purchase_A.csv
  665  cat purchase_A.csv
  666  echo "2025-06-01,Paul Smith,Mouse,5,3000" >> purchase_A.csv
  667  cat purchase_A.csv
  668  cat << EOF > purchase_B.csv
  669  date,manager,item,quantity,price
  670  2025-06-01,Kathy Red,Monitor,3,40000
  671  2025-06-01,Kathy Red,Keyboard,4,5000
  672  EOF
  673  ls
  674  cat purchase_B
  675  cat purchase_B.csv
  676  man head
  677  man tail
  678  clear
  679  head -n 1 purchase_A.csv > merge.csv
  680  ls
  681  cat merge.csv
  682  tail -n +2 purchase_A.csv >> merge.csv
  683  cat merge.csv
  684  tail -n + 2 purchase_B.csv >> merge.csv
  685  tail -n +2 purchase_B.csv >> merge.csv
  686  tail -n +2 purchase_C.csv >> merge.csv
  687  cat merge.csv
  688  clear
  689  cd ..
  690  touch merge_script.sh
  691  vim merge_script.sh
  692  cat merge_script.sh
  693  chmod +x merge_script.sh
  694  lls
  695  ls
  696  cat << EOF > purchase_B.csv
  697  date,manager,item,quantity,price
  698  2025-06-01,Kathy Red,Monitor,3,40000
  699  2025-06-01,Kathy Red,Keyboard,4,5000
  700  EOF
  701  cat << EOF > purchase_A.csv
  702  date,manager,item,quantity,price
  703  2025-06-01,Kathy Red,Monitor,3,40000
  704  2025-06-01,Kathy Red,Keyboard,4,5000
  705  EOF
  706  ls
  707  ./merge_script.sh
  708  ls
  709  cat merge.csv
  710  cat merged.csv
  711  rm merge.csv merged.csv purchase_*.csv
  712  ls
  713  vim merge_script.sh
  714  cat merge_script.sh
  715  celar
  716  clear
  717  ls ./incoming_data/
  718  rm ./incoming_data/merge.csv
  719  ls ./incoming_data/
  720  ls
  721  ./merge_script.sh
  722  vim merge_script.sh
  723  ls ./incoming_data/
  724  cat merge
  725  cat merge_script.sh
  726  ./merge_script.sh
  727  ls
  728  ls ./incoming_data/
  729  cat merged.csv
  730  cat merge.csv
  731  vim merge_script.sh
  732  rm merged.csv
  733  clear
  734  ls
  735  rm merge.sc
  736  rm merge.csv
  737  ls
  738  ls ./incoming_data/
  739  ./merge_script.sh
  740  ls
  741  cat merged.csv
  742  vim merge_script.sh
  743  clear
  744  ls
  745  rm merged.csv
  746  ls ./incoming_data/
  747  ./merge_script.sh
  748  ls
  749  cat 20260605_0140_merged.csv
  750  ./incoming_data/
  751  ls ./incoming_data/
  752  ./merge_script.sh
  753  cat 20260605_0141
  754  cat 20260605_0141_merged.csv
  755  clear
  756  ls
  757  rm 20260605_014*.csv
  758  ls
  759  man rm
  760  vim README
  761  cd ..
  762  scp -r kadai3 -p 2622 sato-yuki@202.247.58.211
  763  ssh -p 2622 sato-yuki@202.247.58.211
  764  le
  765  ls
  766  cd ./kadai3/
  767  ls
  768  vim README
  769  history
  770  ls
  771  vim merge_script.sh
  772  clear
  773  vim merge_script.sh
  774  ls
  775  ./merge_script.sh
  776  ls ./incoming_data/
  777  vim merge_script.sh
  778  clear
  779  ls
  780  scp -P 2622 -r kadai3 sato-yuki@202.247.58.211:kadai_test
  781  cd ./kadai3
  782  vim merge_script.sh
  783  xclip -selection clipboard < merge_script.sh
  784  history
  785  ls
  786  cd ./incoming_data
  787  ls
  788  cat purchase_
  789  cat purchase_A
  790  cat purchase_A.csv
  791  cd ..
  792  vim test_csv_generator.sh
  793  clear
  794  ls
  795  chmod +x test_csv_generator.sh
  796  ./test_csv_generator.sh
  797  ls
  798  ls ./incomgin
  799  ls ./incoming_data/
  800  clear
  801  ls
  802  ./merge_script.sh
  803  ls ./merged_data/
  804  cat ./merged_data/20260605_05
  805  cat ./merged_data/20260605_0503_merged.csv
  806  cd ..
  807  ls
  808  cd ./user001
  809  ls
  810  mkrid lesson15
  811  echo "first file" >> hello.txt
  812  ls
  813  rm hello.txt
  814  cd ./lesson15
  815  mkdir lesson15
  816  cd ./lesson15
  817  echo "hello" >> hello.txt
  818  ls
  819  git init
  820  ls -a
  821  git add hello.txt
  822  git status
  823  git commit -m "initial commit"
  824  git remote -v
  825  git remote add origin https://github.com/youxiberlin/repo15.git
  826  git remote -v
  827  git push
  828  cd ..
  829  ls

~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
".github/workflows/run.yml" [New]                                   0,0-1         All
name: same_test # 実行スクリプト名
  830  rm -r ./lesson15

~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
"test_gcd.sh" 0L, 0B                                                0,0-1         All
#!/bin/bash
  831  y

~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
"gcd.sh" 0L, 0B                                                     0,0-1         All
#!/bin/bash
  832  git clone git@github.com:youxiberlin/repo15.git
#!/bin/bash

echo "This is in gcg.sh"
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
"test_gcd.sh" 3L, 38B                                               3,24          All
#!/bin/bash
  833  cd ./repo15/
  834  touch gcd.sh test_gcd.sh
  835  ls
  836  git add -a
  837  git add -A
  838  git commit -m "initial commit"
  839  ls
  840  git push
  841  mkdir -p .github/workflows
  842  ls
  843  cd ..
  844  ls
  845  cd ./repo15/
  846  ls -a
  847  ls ./.github/
name: same_test # 実行スクリプト名
on: [push] # 実行タイミング
jobs:
io_test:
name: Use Linux commands # テストの名前
runs-on: ubuntu-latest # 実行環境
steps:
-name: Checkout # 処理名（チェックアウト）
uses: actions/checkout@v4 # Runner version 4で実行
-name: Permission Setting # 処理名（権限設定）
run: chmod +x gcd.sh test_gcd.sh # chmodで権限付与
-name: Test Run# 処理名
run: ./test_gcd.sh#
~
~
~
~
~
~
~
~
~
~
~
".github/workflows/run.yml" 13L, 452B                               11,33         All
name: same_test # 実行スクリプト名
on: [push] # 実行タイミング
jobs:
  io_test:
    name: Use Linux commands # テストの名前
    runs-on: ubuntu-latest # 実行環境
    steps:
      - name: Checkout # 処理名（チェックアウト）
        uses: actions/checkout@v4 # Runner version 4で実行
     - name: Permission Setting # 処理名（権限設定）
       run: chmod +x gcd.sh test_gcd.sh # chmodで権限付与
      -name: Test Run# 処理名
      run: ./test_gcd.sh#
-- INSERT --                                                        9,9           All
